// This file is auto-generated by scripts/genVersions.js. Do not edit.

export const PEBBLE_VERSION = "0.1.7";
export const PEBBLE_LIB_VERSION = "0.1.7";
export const PEBBLE_COMMIT_HASH = "59578342c5ad964a7a240cdc80e3291f52003139";
