// This file is auto-generated by scripts/genVersions.js. Do not edit.

export const PEBBLE_VERSION = "0.2.0";
export const PEBBLE_LIB_VERSION = "0.2.0";
export const PEBBLE_COMMIT_HASH = "e90fd1c3957bcf33490505f324c1bfb86d021ba4";
