// This file is auto-generated by scripts/genVersions.js. Do not edit.

export const PEBBLE_VERSION = "0.1.9";
export const PEBBLE_LIB_VERSION = "0.1.9";
export const PEBBLE_COMMIT_HASH = "32225ce152366984bc9ffb9ec32bc3437f588b90";
