import { existsSync, readFileSync } from "node:fs";
import * as path from "node:path";
import { testOptions, COMPILER_VERSION } from "../../IR/toUPLC/CompilerOptions";
import { createMemoryCompilerIoApi } from "../io/CompilerIoApi";
import { Compiler } from "../Compiler";
import { fromUtf8, fromHex } from "@harmoniclabs/uint8array-utils";
import { parseUPLC, UPLCConst, Application } from "@harmoniclabs/uplc";
import { CEKError, Machine } from "@harmoniclabs/plutus-machine";
import { dataFromCbor } from "@harmoniclabs/plutus-data";

// Plutus V4 (Dijkstra) prelude types, validated against the ACTUAL
// encodings produced by plutus-ledger-api 1.68.0.0's `toData`:
// the fixtures in fixtures/v4-data-encodings.json are hex-encoded CBOR
// of real `PlutusLedgerApi.V4` values (generated by a small Haskell
// program building sample contexts — see the `generator` field in the
// JSON). Each test decodes a fixture and reads it back through pebble's
// `*V4` prelude types on the CEK machine, so constructor indices and
// field order are pinned to the released library, not to a hand reading
// of its source.

const fixturesPath = path.resolve(
    __dirname,
    "fixtures/v4-data-encodings.json"
);
const hasFixtures = existsSync( fixturesPath );
const fixtures: Record<string, string> = hasFixtures
    ? JSON.parse( readFileSync( fixturesPath, "utf8" ) ).fixtures
    : {};

async function exportFn( src: string, functionName: string ): Promise<Uint8Array> {
    const ioApi = createMemoryCompilerIoApi({
        sources: new Map([ [ "main.pebble", fromUtf8( src ) ] ]),
        useConsoleAsOutput: false,
    });
    const c = new Compiler( ioApi, { ...testOptions, compilerVersion: COMPILER_VERSION } );
    return await c.export({ entry: "main.pebble", root: "/", functionName } as any );
}

function evalWith( flat: Uint8Array, fixtureName: string ): { ok: boolean; msg?: string; logs: string[] } {
    const hexStr = fixtures[ fixtureName ];
    if( !hexStr ) throw new Error( `missing fixture '${fixtureName}'` );
    const d = dataFromCbor( fromHex( hexStr ) );
    const res = Machine.eval(
        new Application( parseUPLC( flat ).body, UPLCConst.data( d ) )
    );
    return res.result instanceof CEKError
        ? { ok: false, msg: res.result.msg, logs: res.logs }
        : { ok: true, logs: res.logs };
}

async function expectAccept( src: string, functionName: string, fixtureName: string ): Promise<void> {
    const flat = await exportFn( src, functionName );
    const r = evalWith( flat, fixtureName );
    if( !r.ok )
    throw new Error( `${functionName}(${fixtureName}) rejected: ${r.msg ?? ""}\ntraces:\n${r.logs.join( "\n" )}` );
}

const d = hasFixtures ? describe : describe.skip;

jest.setTimeout( 300_000 );

d("Plutus V4 prelude types decode the plutus-ledger-api 1.68 encodings", () => {

    test("ScriptContextV4: 4 fields, script hash, purpose, redeemer", async () => {
        await expectAccept(`
export function checkCtx( d: data ): void {
    const ctx = d as ScriptContextV4;
    assert ctx.scriptHash == #11111111111111111111111111111111111111111111111111111111 else "scriptHash";
    assert ( ctx.redeemer as int ) == 0 else "redeemer";
    const Spend{ ref, optionalDatum } = ctx.purpose;
    assert ref.index == 5 else "purpose ref index";
    assert ref.id == #3333333333333333333333333333333333333333333333333333333333333333 else "purpose ref id";
    const Some{ value: dat } = optionalDatum;
    assert ( dat as int ) == 99 else "spending datum";
}`, "checkCtx", "scriptcontext_full" );
    });

    test("TxV4: new/changed fields (subTxIx, guards, directDeposits, accounts, treasuryDonation)", async () => {
        await expectAccept(`
export function checkTx( d: data ): void {
    const ctx = d as ScriptContextV4;
    const tx = ctx.tx;
    assert tx.id == #3333333333333333333333333333333333333333333333333333333333333333 else "id";
    const Some{ value: ix } = tx.subTxIx;
    assert ix == 3 else "subTxIx";
    assert std.list.length( tx.guards ) == 1 else "guards";
    assert std.linearMap.length( tx.directDeposits ) == 1 else "directDeposits";
    assert std.linearMap.length( tx.accountBalanceIntervals ) == 1 else "accountBalanceIntervals";
    assert tx.treasuryDonation == 17 else "treasuryDonation";
    assert tx.currentTreasury is None else "currentTreasury";
    assert std.list.length( tx.certificates ) == 1 else "certificates";
    assert std.list.length( tx.proposals ) == 1 else "proposals";
}`, "checkTx", "scriptcontext_full" );
    });

    test("POSIXTimeRange: Optional bounds (no interval machinery)", async () => {
        await expectAccept(`
export function checkRange( d: data ): void {
    const ctx = d as ScriptContextV4;
    const r = ctx.tx.validityInterval;
    const Some{ value: lo } = r.fromInclusive;
    assert lo == 1000 else "fromInclusive";
    const Some{ value: hi } = r.untilExclusive;
    assert hi == 2000 else "untilExclusive";
}`, "checkRange", "scriptcontext_full" );
    });

    test("standalone POSIXTimeRange with open bounds", async () => {
        await expectAccept(`
export function checkOpen( d: data ): void {
    const r = d as POSIXTimeRange;
    assert r.fromInclusive is None else "open lower";
    assert r.untilExclusive is None else "open upper";
}`, "checkOpen", "timerange_open" );
    });

    test("TxOutV4 / AddressV4: staking ACCOUNT (a credential), not a stake credential", async () => {
        await expectAccept(`
export function checkOut( d: data ): void {
    const o = d as TxOutV4;
    assert o.value.lovelaces() == 75000000 else "value";
    const InlineDatum{ datum } = o.datum;
    assert ( datum as int ) == 42 else "inline datum";
    const Some{ value: refScript } = o.referenceScript;
    assert refScript == #11111111111111111111111111111111111111111111111111111111 else "refScript";
    const PubKey{ hash } = o.address.payment;
    assert hash == #aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa else "payment";
    const Some{ value: acct } = o.address.stakingAccount;
    const PubKey{ hash: acctHash } = acct;
    assert acctHash == #aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa else "staking account";
}`, "checkOut", "txout" );
    });

    test("AccountBalanceInterval: all four constructors", async () => {
        await expectAccept(`
export function checkAbi( d: data ): void {
    match d as AccountBalanceInterval {
        when LowerBound{ lovelaces }: { assert lovelaces == 1 else "lower"; }
        when UpperBound{ lovelaces }: { assert false else "not upper"; }
        when BothBounds{ from, to }: { assert false else "not both"; }
        when Exact{ lovelaces }: { assert false else "not exact"; }
    }
}`, "checkAbi", "abi_lower" );
        await expectAccept(`
export function checkAbi( d: data ): void {
    match d as AccountBalanceInterval {
        when BothBounds{ from, to }: {
            assert from == 3 else "from";
            assert to == 4 else "to";
        }
        when LowerBound{ lovelaces }: { assert false else "not lower"; }
        when UpperBound{ lovelaces }: { assert false else "not upper"; }
        when Exact{ lovelaces }: { assert false else "not exact"; }
    }
}`, "checkAbi", "abi_both" );
    });

    test("TxCertV4: account-based constructor family", async () => {
        await expectAccept(`
export function checkCert( d: data ): void {
    match d as TxCertV4 {
        when RegAccount{ account, deposit }: {
            const PubKey{ hash } = account;
            assert hash == #aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa else "account";
            assert deposit == 1 else "deposit";
        }
        else: { assert false else "wrong constructor"; }
    }
}`, "checkCert", "cert_reg_account" );
        await expectAccept(`
export function checkCert( d: data ): void {
    match d as TxCertV4 {
        when ResignColdCommittee{ cold }: {
            const PubKey{ hash } = cold;
            assert hash == #aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa else "cold";
        }
        else: { assert false else "wrong constructor (expected index 10)"; }
    }
}`, "checkCert", "cert_resign_cold_committee" );
    });

    test("ScriptPurposeV4 carries the script hash in every constructor", async () => {
        await expectAccept(`
export function checkPurpose( d: data ): void {
    match d as ScriptPurposeV4 {
        when Guarding{ scriptHash, guardIndex }: {
            assert scriptHash == #11111111111111111111111111111111111111111111111111111111 else "scriptHash";
            assert guardIndex == 10 else "guardIndex";
        }
        else: { assert false else "wrong constructor (expected Guarding, index 6)"; }
    }
}`, "checkPurpose", "purpose_guarding" );
        await expectAccept(`
export function checkPurpose( d: data ): void {
    match d as ScriptPurposeV4 {
        when Spending{ scriptHash, ref }: {
            assert scriptHash == #11111111111111111111111111111111111111111111111111111111 else "scriptHash";
            assert ref.index == 5 else "ref";
        }
        else: { assert false else "wrong constructor (expected Spending, index 1)"; }
    }
}`, "checkPurpose", "purpose_spending" );
    });

    test("ScriptInfoV4.Guard carries the whole-batch TopTxInfo at the top level", async () => {
        await expectAccept(`
export function checkGuard( d: data ): void {
    match d as ScriptInfoV4 {
        when Guard{ guardIndex, topTxInfo }: {
            assert guardIndex == 14 else "guardIndex";
            const Some{ value: top } = topTxInfo;
            assert std.list.length( top.subTransactions ) == 1 else "subTransactions";
            const sub = std.list.head( top.subTransactions );
            assert sub.treasuryDonation == 17 else "sub tx donation";
            assert top.simplified.treasuryDonations == 21 else "simplified donations";
            assert std.list.length( top.simplified.scriptPurposes ) == 1 else "purposes";
        }
        else: { assert false else "wrong constructor (expected Guard, index 6)"; }
    }
}`, "checkGuard", "scriptinfo_guarding_top" );
        await expectAccept(`
export function checkGuard( d: data ): void {
    match d as ScriptInfoV4 {
        when Guard{ guardIndex, topTxInfo }: {
            assert guardIndex == 13 else "guardIndex";
            assert topTxInfo is None else "sub-transaction guard has no TopTxInfo";
        }
        else: { assert false else "wrong constructor"; }
    }
}`, "checkGuard", "scriptinfo_guarding_sub" );
    });
});

if( !hasFixtures )
{
    test("v4 fixtures missing — generate with scripts/gen-v4-fixtures (see fixtures README)", () => {
        console.warn(
            "compiler.v4Prelude.test.ts: fixtures/v4-data-encodings.json not found; V4 prelude " +
            "encoding tests were SKIPPED. Generate the fixtures with the plutus-ledger-api 1.68 " +
            "dump program (internal_docs/plutus-v4-status.md)."
        );
    });
}
