// Auto-generate the COMPILER_VERSION constant for the pebble package.
// Reads the package version from package.json.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

async function main() {
    const pkgRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
    const pkgPath = path.join(pkgRoot, "package.json");
    const outPath = path.join(pkgRoot, "src", "version.generated.ts");

    let version = "0.0.0";
    try {
        const pkg = JSON.parse(await readFile(pkgPath, "utf8"));
        version = pkg.version ?? version;
    } catch (e) {
        console.error("Failed to read package version:", e);
    }

    const banner = "// This file is auto-generated by scripts/genVersion.js. Do not edit.\n";
    const content = `${banner}
export const COMPILER_VERSION = "${version}";
`;

    await writeFile(outPath, content, "utf8");
    console.log("Generated", path.relative(process.cwd(), outPath));
}

main();
